name: tools
description: "A collection of tiny tools to get common tasks done really quick!"
publish_to: none
version: 1.0.2+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  rxdart: ^0.27.7
  flutter_dialog_manager: ^1.0.0+4
  dio: ^5.4.2+1
  url_launcher: ^6.2.5
  url_strategy: ^0.2.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  flutter_gen_runner:

flutter_gen:
  output: lib/core/assets
  assets:
    outputs:
      class_name: TinyToolsAssets
      package_parameter_enabled: false

flutter:
  uses-material-design: true
  assets:
    - assets/
